#!/bin/sh
set -e # Exit immediately if a command fails
echo "Running pre-push checks..."
cargo fmt --all -- --check
cargo clippy --all-features --all-targets -- -D warnings
cargo test --all
echo "All checks passed!"
