[alias]
tui = 'run -r -p axon-tui'
server = 'run -r -p axon-server'
smoke-tui = 'run -r -p axon-smoke-tui'
smoke-server = 'run -r -p axon-smoke-server'
smoke-local = 'run -r -p axon-smoke-local-stack'
tui-debug = 'run -p axon-tui'
server-debug = 'run -p axon-server'
smoke-tui-debug = 'run -p axon-smoke-tui'
smoke-server-debug = 'run -p axon-smoke-server'
smoke-local-debug = 'run -p axon-smoke-local-stack'